### ISSUE TITLE
UFO Enemy Unknown AGA

### ISSUE THREAD

**Issue by FenioPL** [rkrajnc/minimig-mist#17]
firmware version: tested on all releases
kickstart version: 3.1
chipRAM: 2mb
fastRAM: 24mb
slowRAM: 0.0mb
game / demo: UFO Enemy Unknown AGA (WHDLoad and floppy version)
description of the problem: Corruption graphics earth globe on "geoscape" in game.

**Comment by rkrajnc** [comment]
Fixed by Till Harbaum's CPU updates.
