### ISSUE TITLE
Fire & Ice - AGA version

### ISSUE THREAD

**Issue by FenioPL** [rkrajnc/minimig-mist#19]
firmware version: ATH150622
kickstart version: 3.1 or 3.0
chipRAM: 2mb
fastRAM: 24mb
slowRAM: 0.0mb
game: Fire & Ice WHDLoad AGA CD32 v2.2 or two ADF version [cr LSD] and [cr Vikings]
WHDLoad version: 18,1
description of the problem: Game freeze few seconds after loading. The same problem on ADF floppy version.

**Comment by rkrajnc** [comment]
Fixed, will be in next release.
