### ISSUE TITLE
HELP key missing?

### ISSUE THREAD

**Issue by juri74** [rkrajnc/minimig-mist#26]
i do not know if this is (reported) bug or not but i wasn't able to find any informations.

•firmware version: Latest
•core version: Latest
•kickstart version: any
•chipRAM: any
•fastRAM: any
•game :Damocles
•other system tested: WinUAE: working, HELP KEY is mapped on PAGDOWN key.
•description of the problem: 
Damocles require pressing HELP KEY to access load/save menu, but after pressing ALL keys on keyboard nothing happended, double checked with KME (http://aminet.net/package/util/misc/kme)
and it appear that HELP key is never pressed.. if it have a keycode i could remap to some other keys (like winuae i would use PAGDOWN key) but i do not know the keycode.

EDIT: i noticed that keypad keys " [ " and " ] " are apparently not mapped too
thanks
Juri

**Comment by rkrajnc** [comment]
Hi,

honestly, I never used the help key until now ;) It's possible that the mapping is missing, I'll check it out and add a map Help -> PAGEDOWN.

**Comment by rkrajnc** [comment]
Can you try the firmware attached (rename it to firmware.upg), the HELP key should be mapped to PAGEDOWN.

![firmware upg](https://cloud.githubusercontent.com/assets/941597/11361895/a30bf916-9290-11e5-910b-6b97572434e2.png)

**Comment by juri74** [comment]
hello, unfortunately it doesn't work... :'(
now pressing HELP key HRTMon is activated, F11 do not activate it anymore.. i tried to disable it and i noticed that the HRTmon option already reported as deactivated!!! i renamed  it but when i press PAGDOWN amiga crash with guru code 8000 000B 0000 8922
i have an italian keyboard but i don't think this is the problem since all other keys have worked before without problem..

**Comment by rkrajnc** [comment]
Ok, it's not a simple fix then ;) I forgot that NMI (F11) handling is done in the FPGA core, so an FPGA update will be needed. I'll let you know when I'll fix it.

**Comment by juri74** [comment]
thank you very much! :)

**Comment by rkrajnc** [comment]
Fixed in minimig_mist-1_2 (https://github.com/rkrajnc/minimig-mist/commit/da69f6ec45f9956f1df56f0a9a7f4a062c9b726e).
