### ISSUE TITLE
GM 810000FF with Classic Workbench Full v28

### ISSUE THREAD

**Issue by ArKay74** [rkrajnc/minimig-mist#31]
Getting an 810000FF after the Workbench screen is opened. 

810000FF : A quick interrupt has happened to an uninitialised vector

I can supply a compressed HDF if needed.

**Comment by rkrajnc** [comment]
Did you try the new release, do the problems still persist?

**Comment by ArKay74** [comment]
Of course I have formatted the SD card since trying the installation. Is 
this supposed to be fixed then?
I could give it another try when I find the time for it.

------ Original Message ------

**Comment by ArKay74** [comment]
Well, this time it worked. That could probably also be due to the fact that I didn't activate the AGA Copper  background effect. Could that have been it?

**Comment by rkrajnc** [comment]
The copper background shouldn't be a problem, but I think you can still enable it in the menu (the option should be Copper). Can you try enabling it and report if there are any problems?

**Comment by ArKay74** [comment]
After the previous installation the harddisk image didn't even work in WinUAE so I have no idea what went wrong (there were only some weird bars on the screen). Anyway, I did a re-installation with AGA coppers activated and so far it has been stable. It's probably safe to close this bugreport.
