### ISSUE TITLE
MinimigAGA 1.2: no write protection for floppy discs

### ISSUE THREAD

**Issue by AmigaIstMiST** [rkrajnc/minimig-mist#45]
https://github.com/mist-devel/mist-binaries/issues/8

**Comment by rkrajnc** [comment]
Hi,

I'm sorry I didn't see this sooner.

There is a way to write-protect the floppy images - you set the read-only attribute on the .adf file. This has been supported from the beginning.

**Comment by AmigaIstMiST** [comment]
Ah OK. The Atari ST core has a the option to switch it on on OSD, but of course the Minimig works differently. Using the attribute on the file should indeed be enough to prevent a virus epidemy. I had the Taipan bootblock virus spreading over my adf files, there was a virus dropper hidden on one of the utility disks I downloaded :-)
