### ISSUE TITLE
Scandoubler OFF during boot phase

### ISSUE THREAD

**Issue by sblendorio** [rkrajnc/minimig-mist#49]
Is it possibile to have 15kHz output also during boot, before the cores run?

**Comment by rkrajnc** [comment]
It should be possible, but some bug that I haven't found yet prevents this from working. I'll try to fix it.

**Comment by AmigaIstMiST** [comment]
Solved with the latest firmware update 170113.

**Comment by rkrajnc** [comment]
Fixed here: https://github.com/mist-devel/mist-firmware/commit/9b673e65e0d3e2a75b07ca3ab85f1cafaa020b1f
