### ISSUE TITLE
Can't save configurations

### ISSUE THREAD

**Issue by sardaukar** [rkrajnc/minimig-mist#50]
I can use the core perfectly, but for some reason configurations never get saved :| I'm using an 8GB SDHC card. 

Can I create the files by hand somehow? If so, how?

Thanks for any help!

**Comment by sardaukar** [comment]
Using version 1.2 from the website, by the way, and the latest MiST firmware.

**Comment by EricGus** [comment]
Which core?

**Comment by sardaukar** [comment]
Fixed this - copied the files over to a 512MB SD card, could save configs, copied them to my 8GB SD card and now everything works!
