### ISSUE TITLE
Minimig-AGA v1.2: Bar / stripes pattern in dark backgrounds

### ISSUE THREAD

**Issue by mambrino** [rkrajnc/minimig-mist#53]
Hi,

I found an annoying problem with minimig-AGA core v1.2. With scandoubler activated in dark consistent color backgrounds a kind of vertical bars/stripes pattern appears. I've tried this with Minimig board and doesn't occur.

Here is a picture in which you can see the effect (Demo: Enjoy The Silents / WHDLoad & ADF):

![mist](https://cloud.githubusercontent.com/assets/19496893/17110523/b530a0e2-529d-11e6-9999-dbd6cb2669cb.jpg)

And this is with minimig board (no problem):

![minimig](https://cloud.githubusercontent.com/assets/19496893/17110529/bf611d26-529d-11e6-8f31-3be198a7d381.jpg)

Tested with different cables / monitors, and it's not a problem related to this.

Thanks ;)

**Comment by rkrajnc** [comment]
Are you sure this isn't caused by your monitor? Can you try on another monitor, possibly a CRT? Alternatively, you could try changing your monitor clock phase setting, that usually fixes it.

**Comment by mambrino** [comment]
Tested with LG M1921A, M1721A and Panasonic TX-L32ET5 (only works with scandoubler disabled). After testing, I've found that disabling scandoubler the pattern disappears. Maybe is related to this.

Sorry, but these monitors don't have clock phase adjusting (only Panasonic TX-L32ET5, but not in SCART mode).

Thanks ;)

**Comment by rkrajnc** [comment]
Can you try changing your monitor's clock phase setting, and see if the pattern moves? If it does, it is caused by your monitor, and you can try to eliminate it by adjusting the clock offset.

If it does not, and it shows even with dithering disabled, then it is a completely new bug, but one I have never seen myself.

**Comment by mambrino** [comment]
Tested with a CRT monitor and no pattern at all. Probably is a problem of these two monitors. But, how is possible that on the same monitor with minimig board this doesn't happen?

Thanks ;)

**Comment by rkrajnc** [comment]
It is possible that the original minimig and the MiST board don't have exactly the same frequency down to the last Hz, that is why it works on one board and not another - even a very small difference could cause this.
