### ISSUE TITLE
Amiga core and MIDI output

### ISSUE THREAD

**Issue by sblendorio** [rkrajnc/minimig-mist#55]
Hi,

I tried to use DeluxeMusic Construction Set using the MIDI ports of MIST, but every time I try to make it play through MIDI, I get a Guru Meditation.

Should I install some driver or set some system preference? Is there some game/demo I could use to test MIDI ports?

Thanks in advance.

**Comment by sblendorio** [comment]
Hi, now I have a configuration that doesn't "GURUs", but still no sound is emitted from MIDI keyboard (while using ATARI core it's a simple "plug and play" literally). The software is "Deluxe Music 2", and this is the configuration of MIDI/Serial port I used.

Did you see something wrong? Do you know some DEMO that I can use to test MIDI?

![ximg_20160820_155215](https://cloud.githubusercontent.com/assets/2118813/17831840/9fc14b60-66f4-11e6-9245-4c434a03d8d8.jpg)

![ximg_20160820_155229](https://cloud.githubusercontent.com/assets/2118813/17831841/9fc4961c-66f4-11e6-9d63-2cd6932f8831.jpg)

![ximg_20160820_155300](https://cloud.githubusercontent.com/assets/2118813/17831842/9fc5a6ba-66f4-11e6-8bf6-21ef834e99e5.jpg)

**Comment by kowoba** [comment]
Doesn't this need camd.library installed?

**Comment by kowoba** [comment]
The "old" library package:
http://aminet.net/package/mus/edit/camd

The "new" (and open sourced) library package:
http://aminet.net/package/mus/midi/camd40

**Comment by sblendorio** [comment]
The "old" library package:
http://aminet.net/package/mus/edit/camd

...worked GREAT! THANK YOU!

**Comment by sblendorio** [comment]
The "old" library package:
http://aminet.net/package/mus/edit/camd

...worked GREAT! THANK YOU!
My keyboard playing though MiST:
https://www.youtube.com/watch?v=ZZIXUOduVCE

![xximg_20160821_114718](https://cloud.githubusercontent.com/assets/2118813/17836567/8306bca0-6797-11e6-8fdb-974775d653e4.jpg)

**Comment by kowoba** [comment]
Awesome! 👍 Glad I could help :)
