### ISSUE TITLE
ADF file corruption on some SD cards long term solution

### ISSUE THREAD

**Issue by AmigaIstMiST** [rkrajnc/minimig-mist#62]
It's a known issue that minimig/MiST has problems with corrupt ADF files when using larger SD cards. I had the same problem and solved it by moving to a smaller SD card with 2 GB capacity (thanks to a hint by chaos :-) ).
I don't know why this problem exists when using some SD cards, but I think there should be a 100% solution that works with all SD cards. The current situation is really frustrating especially to new users. On some forum entries, users report that they had to try (=buy) several SD cards, before they found one that was reliable. What about this:
- when an ADF image is inserted, copy the image to a dedicated part of the MiST RAM
- all read/write operations use the RAM image
- when removing the ADF image, the modified copy from RAM is synced to the SD card in a safe way, before the ADF image is ejected

This is just what comes to my mind, when I think about this problem. Maybe other/simpler solutions exist.

**Comment by rkrajnc** [comment]
Hi,

First of all, thanks for all your bug reports,  I appreciate it.

This is probably not a size issue,  ss I am successfully using a 16GB SD card.  It seems some cards are just different then others,  but what exactly is the difference,  I don't know, as I have a bunch of them and they all work,  from 32MB to 16GB.

It could be a ARM -> SD card timing issue,  I'll look into that first.

**Comment by AmigaIstMiST** [comment]
I had this problem with a SANDISK 8Gb SD card.
2GB SONY works fine.

**Comment by lotharsm** [comment]
I had this issue with some cards, a 32GB Sandisk, a 2GB Sandisk and a (I think) 16GB Kingston.

A permanent solution for this would be really great, because none of my SD cards worked properly on the MiST. I would really appretiate a fix!

**Comment by AmigaIstMiST** [comment]
Hi chaos,

do you think this is an Amiga only problem? Or is this a general MiST problem, that affects the AtariST, too? If yes, maybe the MiST repo would be a better place to report this.

**Comment by AmigaIstMiST** [comment]
Hi @rootfather ,
Lotharek and dragonbox sell SD cards especially for the MiST, maybe you should buy one of these.
Lotharek claims on his site, that the main problem are faked sd cards of bad quality.


http://lotharek.pl/products.php?kid=29
https://www.dragonbox.de/de/36-sd-karten

Could this be the problem? Too many faked cards of bad quality out there?

**Comment by AmigaIstMiST** [comment]
Nearly all read errors I had on ADFs went away with V1.2.3! I assume, this bug is fixed now. MinimigAGA is becoming perfect after all these years :-)
