### ISSUE TITLE
minimig core and analog joysticks

### ISSUE THREAD

**Issue by sblendorio** [rkrajnc/minimig-mist#81]
Are Amiga analog-joysticks recognized by MIST-minimigAGA? The pinout is this (I think "PADDLE" column):
https://allpinouts.org/pinouts/connectors/input_device/mouse-joystick-amiga-9-pin/

**Comment by rkrajnc** [comment]
Unfortunately, not all the required joystick signals are connected on the MiST board, so this will not be possible.
