### ISSUE TITLE
USB joystick disables DB9 mouse

### ISSUE THREAD

**Issue by AmigaIstMiST** [rkrajnc/minimig-mist#82]
- plugin a real DB9 Amiga ("tank") mouse

Result: the mouse works, everything is fine

- plugin a USB joystick/joypad additionally to the DB9 Amiga mouse

Result: the USB joystick disables the DB9 Amiga mouse!
If you unplug the USB joystick, the DB9 Amiga mouse works again.

**Comment by AmigaIstMiST** [comment]
Tested with firmware ATH170207 and MinimigAGA cor 1.2.2 BETA.

**Comment by rkrajnc** [comment]
Hi,

yes there is some code in the firmware that reorders joysticks / mice when an USB device is plugged in. It's annoying, I agree. I'll take a look at it and try to come up with a solution.

**Comment by rkrajnc** [comment]
Hi,

try to update your MiST firmware with the attached file (unzip it to the root of your SD card and run firmware upgrade in the OSD menu), and add an entry to your mist.ini file, under the [mist] section:
`joystick0_prefer_db9=1`

I only tried it with a joystick in JOY1 and AAA, but it should work with a mouse also. Please report if it works for you so I can close the issue and push the code.

[firmware.zip](https://github.com/rkrajnc/minimig-mist/files/1327648/firmware.zip)

**Comment by AmigaIstMiST** [comment]
Man, thats fast! 😊
I will test it tomorrow evening.

Am 24.09.2017 21:24 schrieb "Rok Krajnc" <notifications@github.com>:

**Comment by AmigaIstMiST** [comment]
Ok, I tested all 4 possible combinations of USB/DB9 mice and joysticks:

- usb mouse, usb joypad
- usb mouse, db9 joystick
- db9 mouse, usb joypad
- db9 mouse, db9 joystick

Everything works as expected!

However, it is a little odd, that an extra INI entry is needed for this. I think, this this the expected behavior!

**Comment by rkrajnc** [comment]
Hi,

thanks for testing this. Actually, the extra ini setting is really needed, as the firmware can't automatically detect DB9 - connected devices, so if a USB joystick is present, it has to assume that no DB9 joysticks are present and make the USB device the primary joystick (so at least one device works).

That is how the firmware works without the new ini entry - as soon as one USB device is present, it makes it joystick number two, and makes DB9 JOY1 the third device. The new ini entry disables this joystick reordering.

Theoretically, the firmware could detect the DB9 - connected mouse or joystick when it would detect direction movement or a button press and then reorder the devices, but that would make it even more confusing, so for now, this solution should do.

**Comment by rkrajnc** [comment]
Fixed in MiST firmware with commit [23ad06e0](https://github.com/mist-devel/mist-firmware/commit/23ad06e0fdaa629092f97c9aca62b32a522bf6ff).

**Comment by AmigaIstMiST** [comment]
Can the firmware detect the difference between a USB mouse and a USB joystick?
If yes, what about this simple logic:

Is a USB mouse present? If no, assume a DB9 mouse in the first DB9 port.

**Comment by AmigaIstMiST** [comment]
Hmm, but this could cause problems with the C64 core, where normally no mouse is attached at all, so forget my comment. At least it is possible now to use the Amiga mouse as main mouse. As it is possible now to turn your old Amiga mouse into a laser mouse with these new laser upgrade kits, this is becoming more important now.

**Comment by AmigaIstMiST** [comment]
What about releasing the firmware as a binary ? :-)

**Comment by rkrajnc** [comment]
What do you mean? The binary is 5 posts up, the [firmware.zip](https://github.com/rkrajnc/minimig-mist/files/1327648/firmware.zip) link.

**Comment by AmigaIstMiST** [comment]
I mean: making it public in the official MiST repo. You did a code check
in, but you did not check in the binary.

Am 03.11.2017 11:37 AM schrieb "Rok Krajnc" <notifications@github.com>:
